#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

# Remove all generated cases, logs, meshes, and results
rm -rf -- runs

#------------------------------------------------------------------------------
